### ISSUE TITLE
Error checking

### ISSUE THREAD

**Issue by apocatarsis** [RaulPPelaez/Naga_KeypadMapper#19]
We should add some error checking once in a while during the execution, to check if the device is still present (stopping/pausing the execution until it is back online) or has changed between the docking/plugged mode.

And we should also do error checking in every step of the initialization.

**Comment by Destroyer** [comment]
I think we can try to look for connected devices instead and if there're any and we are successful in opening them, we can continue execution. Ofc if the devices are plugged out we exit completly and after they're plugged back in systemd should start the daemon again (related to #20 ) .

**Comment by Destroyer** [comment]
Should be also fixed with #20 in https://github.com/Destroyer/Naga_KeypadMapper/commit/24b8baa2579cbf51a6dccc65e2407eb8dd7891ac

**Comment by RaulPPelaez** [comment]
Agree.
