### ISSUE TITLE
Modifier keys (shift/ctrl/alt/...) for extra functionality?

### ISSUE THREAD

**Issue by ipsod** [RaulPPelaez/Naga_KeypadMapper#36]
Would it be possible to add modifier key shortcuts to the mappings?  Not modifiers on the mouse, but holding down keyboard modifiers while hitting mouse buttons.

Something like:
1 - workspace_r=1
S1 - workspace_r=-1
C1 - workspace=0
CS1 - workspace=2

**Comment by apocatarsis** [comment]
Yes I think this is a good idea. I think this can be done with xev, I do not know right now how to call it from c++, should not be too hard using something like XGrabKey().
Thanks for the suggestion!

**Comment by RaulPPelaez** [comment]
I think this can be done know using the toggle function. Please reopen otherwise!
