### ISSUE TITLE
Keys Numpad and normal keys

### ISSUE THREAD

**Issue by Dante2333** [RaulPPelaez/Naga_KeypadMapper#41]
This is the mapping I'm using:

1 - key=KP_1
2 - key=KP_2
3 - key=KP_3
4 - key=KP_4
5 - key=KP_5
6 - key=KP_6
7 - key=KP_7
8 - key=KP_8
9 - key=KP_9
10 - key=KP_0
11 - key=KP_Subtract
12 - key=KP_Add

I'm trying to actually use 2 and KP_2 as 2 different options in Dota 2; it seems that KP_2 also does the function as 2 so I can't have 2 options with this configuration, do anybody think this could be fixed and related to Naga mapper or there's no way to avoid this from linux kernel detecting the numpad and key as the same? I did verify this idea with xev, xev denotes KP_2 and 2 as actually 2 different keys.

**Comment by TheGuardianWolf** [comment]
Try mapping KP_End etc instead of the numbers.

**Comment by ReynaldoJose** [comment]
Thanks Wolf, tried that, does not work;
(symbol) No such key name 'KP_INSERT'. Ignoring it.
(symbol) No such key name 'KP_PGUP'. Ignoring it.
(symbol) No such key name 'KP_DOWNARROW'. Ignoring it.
(symbol) No such key name 'KP_INSERT'. Ignoring it.
(symbol) No such key name 'KP_HOME'. Ignoring it.

**Comment by TheGuardianWolf** [comment]
That is the xdotool reporting that the keys don't exist, but I've currently got them bound via the razer driver package, I'll boot up my install and see what they are.

**Comment by TheGuardianWolf** [comment]
Alright here we go, the names are case sensitive - see my xdotool key bindings:
https://imgur.com/a/QY1Z8

Then in my dotes:
https://imgur.com/a/fAxZk

**Comment by apocatarsis** [comment]
The available keys are the ones from xdotool in its nomenclature (removing the starting XK_). Here is a list of all available keys:
[](https://cgit.freedesktop.org/xorg/proto/x11proto/plain/keysymdef.h)
You can test them by using xdotool with the command:
`$ xdotool key --window getactivewindow KEY`
This is simply what the daemon does, so if it works in the cli, it will work with naga.

In your case, these are the keys for the numpad:
```
#define XK_KP_Space                      0xff80  /* Space */
#define XK_KP_Tab                        0xff89
#define XK_KP_Enter                      0xff8d  /* Enter */
#define XK_KP_F1                         0xff91  /* PF1, KP_A, ... */
#define XK_KP_F2                         0xff92
#define XK_KP_F3                         0xff93
#define XK_KP_F4                         0xff94
#define XK_KP_Home                       0xff95
#define XK_KP_Left                       0xff96
#define XK_KP_Up                         0xff97
#define XK_KP_Right                      0xff98
#define XK_KP_Down                       0xff99
#define XK_KP_Prior                      0xff9a
#define XK_KP_Page_Up                    0xff9a
#define XK_KP_Next                       0xff9b
#define XK_KP_Page_Down                  0xff9b
#define XK_KP_End                        0xff9c
#define XK_KP_Begin                      0xff9d
#define XK_KP_Insert                     0xff9e
#define XK_KP_Delete                     0xff9f
#define XK_KP_Equal                      0xffbd  /* Equals */
#define XK_KP_Multiply                   0xffaa
#define XK_KP_Add                        0xffab
#define XK_KP_Separator                  0xffac  /* Separator, often comma */
#define XK_KP_Subtract                   0xffad
#define XK_KP_Decimal                    0xffae
#define XK_KP_Divide                     0xffaf

#define XK_KP_0                          0xffb0
#define XK_KP_1                          0xffb1
#define XK_KP_2                          0xffb2
#define XK_KP_3                          0xffb3
#define XK_KP_4                          0xffb4
#define XK_KP_5                          0xffb5
#define XK_KP_6                          0xffb6
#define XK_KP_7                          0xffb7
#define XK_KP_8                          0xffb8
#define XK_KP_9                          0xffb9


```

**Comment by apocatarsis** [comment]
About the difference between KP_2 and 2, does dota recognizes the two "2" keys as different? (with a regular keyboard, that is)

**Comment by TheGuardianWolf** [comment]
You can see by my second screenshot that it does indeed, I'm pretty sure OP just needs to fix the case on the xdotool macros and they should be good to go.

**Comment by apocatarsis** [comment]
@TheGuardianWolf Yep, seems like it.
BTW, your first screenshot is cool. With "razer driver" are you refering to this project? [](https://github.com/terrycain/razer-drivers)

I did not knew about it but it seems pretty pro! It appears as if it allows to do the same as my project, is that so?

**Comment by ReynaldoJose** [comment]
I can't be happier, @apocatarsis you have made possible my full transition to linux with this script; please, spare me an ethereum address or bitcoin address ill send something on your way.
@TheGuardianWolf you were right, btw I did install the razer driver but it does not do anything for me. My mouse has no other options but to change lights and stuff and I already had razerd installed which does the same thing for me.

**Comment by TheGuardianWolf** [comment]
@apocatarsis The project here: 

https://github.com/terrycain/razer-drivers 

is what I'm talking about.

Basically along with some other low level driver stuff, it opens up some python bindings that this program uses:

https://github.com/GabMus/razerCommander

and I can assign macros using that. This project is a lot more minimalistic and what I first used before the razer drivers had compatibility with my Naga Hex, since I actually can modify the code here vs the low level driver stuff.

**Comment by ReynaldoJose** [comment]
@TheGuardianWolf I'll try that in the future, I actually prefer the naga_keymapper as I do not have chroma or anything like that.

**Comment by apocatarsis** [comment]
@TheGuardianWolf Yes, I was refering to that project. For some reason the link did not showed up. Thanks!
@ReynaldoJose Thanks very much for your kind words, I am glad you found it useful. You have my wallet in my bio, but you do not owe me anything, srsly.
