### ISSUE TITLE
Toggle and bash actions

### ISSUE THREAD

**Issue by TheGuardianWolf** [RaulPPelaez/Naga_KeypadMapper#43]
Hey there, I've managed to write code for toggle and bash commands.

Would you mind testing and debugging this if you have the naga device? It should work theoretically I think.

https://github.com/TheGuardianWolf/Naga_KeypadMapper

'toggle' is the keyword for the toggle action.
'bash' is the keyword for the bash action, and runs the command ```bash -c "<yourcommandhere>"```

**Comment by apocatarsis** [comment]
Yeah pretty good! Thanks!! , I do not have a naga mouse to check right now, but I will test it when I can.
The key state vector is a nice addition I believe.
The bash option is already implemented though, it was one of the original problems I wanted to solve. I call it "run" option. You can use it to run any command (like firefox), but bash is just a command after all so run can have:
10 - run=bash whatever_script.bash

BTW, can you put this as a pull request?

**Comment by TheGuardianWolf** [comment]
Oh I see, I can remove my bash thing. I'll pull after.

**Comment by Destroyer** [comment]
No, it's because of macro support, see https://github.com/apocatarsis/Naga_KeypadMapper/pull/13

**Comment by RaulPPelaez** [comment]
This is merged and working now.  #44   #42  I do not know how to mention commits here...
Thank you!
