### ISSUE TITLE
Code Lacks a Licence

### ISSUE THREAD

**Issue by Ameliorate** [RaulPPelaez/Naga_KeypadMapper#49]
The closest thing to a licence this has is the header at the top of naga.cpp:

```
/*
 * Apocatarsis 2016
 * Released with absolutely no warranty, use with your own responsibility.
 * 
 * This version is still in development
 */
```

You can choose a licence at https://choosealicense.com/, however you'll need to get the permission of all of the people who contributed to Naga_KeypadMapper.

Without a licence, it is technically illegal for others to use or modify your software.

**Comment by RaulPPelaez** [comment]
Thanks for your suggestion @Ameliorate, I added a license. I hope it is fine with everyone.

**Comment by RaulPPelaez** [comment]
I do not want to include anyones name in any place without explicit permission, so If you contribute feel free to add your name in the header.
