### ISSUE TITLE
Syntax for Numpad

### ISSUE THREAD

**Issue by eliaskuz** [RaulPPelaez/Naga_KeypadMapper#58]
Can you please help to solve an issue? 
Snippet does not work:
`key=ctrl+alt+Num_1`
What's the syntax for num?

**Comment by ipsod** [comment]
From the readme:

**KEYBOARD FUNCTION (key)**
For mapping a key from keyboard you need to look up your key e.g. here: http://cgit.freedesktop.org/xorg/proto/x11proto/plain/keysymdef.h .
