### ISSUE TITLE
Support on Wayland ? 

### ISSUE THREAD

**Issue by Nekenlight** [RaulPPelaez/Naga_KeypadMapper#65]
Hi,

Do you have in you're road map the wayland / libinput integration ? 

Actually, only libinput list the device Naga. Xinput is not usable with wayland in the newer version of fedora. 
I use Fedora 29 and Wayland.

Maybe there is a way to bind libinput to xinput ? but Idon't think so.

Best regards ! 👍

**Comment by RaulPPelaez** [comment]
I do not know the first thing about wayland, but the same principle is applicable. There are probably equivalent commands to the xinput lines this project uses. In fact there are only three or four commands that would need to be ported if I am not mistaken. If you know Wayland you can try to go command after command in nagastart.sh and install.sh and see if you can produce the expected lines using wayland commands.
The hassle will probably be replacing xdotool though.
I think this will be easier to do than somehow tricking wayland into using xinput.
Please feel free to reopen if you are interested!

**Comment by perfect7gentleman** [comment]
diff -Nuar nagastart.sh nagastart_wl.sh 
```
--- nagastart.sh        2019-04-28 21:56:05.829230973 +0700
+++ nagastart_wl.sh     2020-04-08 11:51:28.624039642 +0700
@@ -5,7 +5,7 @@
 # xinput set-int-prop $NAGAID1 "Device Enabled" 8 0
  
 # Insanity, just because naga 2014
-NAGAID2=$(xinput | grep Naga | grep pointer | cut -d= -f2 | cut -f1)
+NAGAID2=$(xinput | grep xwayland | grep pointer | cut -d= -f2 | cut -f1)
 if [[ `echo $NAGAID2 | wc -w` -eq 2 ]]; then
 if [[ `xinput get-button-map $(echo $NAGAID2 | awk '{print $1}') | grep 10 | wc -l` -eq 1 ]]; then
 xinput set-button-map $(echo $NAGAID2 | awk '{print $1}') 1 2 3 4 5 6 7 11 10 8 9 13 14 15
```
